name: bc_transporter_mobile
description: App mobile ufficiale di BC Transporter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core
  provider: ^6.0.0
  http: ^1.6.0
  intl: ^0.18.0
  equatable: ^2.0.5
  
  # Map & Location
  webview_flutter: ^4.4.2
  geolocator: ^10.1.0
  url_launcher: ^6.2.0
  
  # UI
  sliding_up_panel: ^2.0.0+1
  glassmorphism: ^3.0.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.5.4
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
